frontend:
	bash Components/frontend.sh
Cart:
	bash Components/Cart.sh
Catalogue:
	bash Components/Catalogue.sh
dispatch:
	bash Components/dispatch.sh
mongodb:
	bash Components/mongodb.sh
mysql:
	bash Components/mysql.sh
payment:
	bash Components/payment.sh
rabbitmq:
	bash Components/rabbitmq.sh
redis:
	bash Components/redis.sh
shipping:
	bash Components/shipping.sh
user:
	bash Components/user.sh
